### ISSUE TITLE
Deduplicate DOHMH data

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#142]
I.e. Should Bright Horizons At Adams Street be two records?
One that's "Group Day Care - Infants/Toddlers" and a second that's "Group Day Care - Preschool"

**Comment by baolingz** [comment]
@AmandaDoyle I think they should be kept as two records since:
1. They were two individual records in the old file.
2. They have different `day_care_id`, which has been used as the unique identifier in the deduplication process
3. The two facilities have distinguished values in several attributes - `age_range`, `maximum_capacity`, `program_type`, `violation_rate_percent`, `permit_number`, `total_educational_workers` and etc.
