### ISSUE TITLE
Improve the location of the point

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#148]
Consider taking the BIN centroid so that the point of facilities fall on the building
Chris R has a BIN centroid file that we might be able to use

**Comment by AmandaDoyle** [comment]
@croswell81 @aferrar Where open data is the BIN footprint centroid point shapefile?

@SPTKL @baolingz Use the point shape from that open data file to assign the geometry to FacDB records by joining by BIN, then recompute the Lat and Long and X/Y so that it agrees with the geometry.  Happy to help with that last step if needed.

**Comment by croswell81** [comment]
@AmandaDoyle We bring that Building Footprint centroid in weekly. It is available on the M drive. If you would like us to make it available in PostGRES @aferrar can add that to the list of data we push.

The data is available on Open Data: https://data.cityofnewyork.us/Housing-Development/Building-Footprints/nqwf-w8eh The download is a little weird because it contains both full footprint polygons and the centroids, so they need to separated.

**Comment by AmandaDoyle** [comment]
@croswell81 Ah okay, yes that is confusing, which is why I didn't think this was correct.

We'll grab the file from open data.  Thanks!

@SPTKL @baolingz Use the point portion of the building footprints file

**Comment by AmandaDoyle** [comment]
@baolingz is this closed?  If so, go ahead and close it out
