### ISSUE TITLE
nysdoh_nursinghomes

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#31]
- [x] s3
- [ ] py
- [ ] sql

https://health.data.ny.gov/Health/Nursing-Home-Weekly-Bed-Census-Last-Submission/izta-vnpq/data

**Comment by AmandaDoyle** [comment]
@SPTKL  nysdoh_nursinghomes

**Comment by baolingz** [comment]
@AmandaDoyle @SPTKL cannot find the sql template in db-facilities repo

**Comment by AmandaDoyle** [comment]
@baolingz @SPTKL 

Field mapping:

- [ ] facname = Facility Name,
- [ ] factype = Bed Type / Service Capacity,
- [ ] facsubgrp = Residential Health Care or Other Health Care depending on the Bed Type,
- [ ] facgroup = NULL,
- [ ] facdomain = NULL,
- [ ] servarea = NULL,
- [ ] opname = ??,
- [ ] opabbrev = ??,
- [ ] optype = NULL,
- [ ] overagency = NYS Department of Health,
- [ ] overabbrev = NYSDOH,
- [ ] overlevel = NULL,
- [ ] capacity = Total capacity,
- [ ] captype = Bed Type / Service Capacity,
- [ ] proptype = NULL

Do note that there are going to be a lot of duplicates in this dataset because a unique value is the Facility + Bed Type / Service Category and there are 10 Bed Type / Service Category per Facility

1) we only want to capture records for each Facility where the Total capacity is > 0
2) in cases where there are multiple records for a facility where the Total capacity is > 0 then we want to think of how to merge the records

Example:
Rutland Nursing Home, Inc. at 585 Schenectady Ave in BK has 10 records, but only 6 are valid and we want to think about how to merge these 6 records into one.

Looping in @lseirup to get her input on how to collapse capacity values

**Unique Bed types are:**
Total Adult Day Health Care Capacity
Total Residential Beds
Total Dialysis Capacity
Total Pediatric Beds
Total Scatter Ventilator Beds
Total Ventilator Beds
Total Traumatic Brain Injury (TBI) Beds
Total Pediatric Ventilator Beds
Total Coma Recovery Beds
Total Behavioral Intervention Beds

**Comment by AmandaDoyle** [comment]
@SPTKL @baolingz 
@lseirup - can you confirm?
Here's how to handle the duplication problem:
Only take the `Total Residential Beds` record and total capacity value for each facility and this becomes a Nursing home facility (no record has a `Total Residential Beds` where`total capacity` = 0) 

Where the `total capacity` > 0 for a `Total Adult Day Health Care Capacity` record for a facility, this becomes a separate facility (a second record) with the use being Adult Day Health Care

**Comment by AmandaDoyle** [comment]
@lseirup confirms logic above ^

**Comment by baolingz** [comment]
@AmandaDoyle could you please update the sql field mapping after applying the above logic?

**Comment by AmandaDoyle** [comment]
Noting that questions were addressed in comment made on May 22nd
