### ISSUE TITLE
hra_centers

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#64]
@SPTKL can we scrape the data from here? https://www1.nyc.gov/site/hra/locations/locations.page

We can also get some datasets from open data
https://data.cityofnewyork.us/browse?q=HRA&sortBy=relevance
Job Centers
Medicaid Offices

Each dataset should have their own python and SQL script

- [x] s3
- [ ] py
- [ ] sql

**Comment by AmandaDoyle** [comment]
Scrape data from each of the individual pages from this website: https://www1.nyc.gov/site/hra/locations/locations.page
And get the following attributes:
Facility name, Address, house number, street name, city, state, zip code, type

I.e. Concourse S45: 1375 Jerome Avenue, 2nd Fl., Bronx, NY 10452 on this page https://www1.nyc.gov/site/hra/locations/snap-locations.page becomes
Concourse S45, 1375 Jerome Avenue, 2nd Fl., 1375, Jerome Avenue, Bronx, NY, 10452, SNAP Center

**Comment by baolingz** [comment]
- SNAP Centers: use kml file over web scraping, caused kml has 2 more records than the latter one
- CASA Offices: use kml file over web scraping, information from both sources are identical
- HASA Centers: use kml file, which is the only data source
- Job Centers: use kml file over NYC Open Data, caused kml has 2 more records than the latter one
- Medicaid Offices: use NYC Open Data over kml file, caused NYC Open Data has 2 more records than the latter one
- OCSS Centers: use kml file over web scraping, information from both sources are identical

**Comment by baolingz** [comment]
@AmandaDoyle Since we are gonna build separate data pipelines for hra datasets, we need to define the following columns for the six datasets (SNAP Centers, CASA Offices, HASA Centers, Job Centers, Medicaid Offices, OCSS Centers) in the sql scripts.

- [ ] facname = facility_name,
- [ ] factype = ??,
- [ ] facsubgrp =(CASE
		               WHEN type = 'Job Centers' THEN 'Workforce Development'
		               ELSE 'Financial Assistance and Social Services'
	                    END),
- [ ] facgroup = NULL,
- [ ] facdomain = NULL,
- [ ] servarea = NULL,
- [ ] opname = 'NYC Human Resources Administration/Department of Social Services',
- [ ] opabbrev = 'NYCHRA/DSS',
- [ ] optype = 'Public',
- [ ] overagency = 'NYC Human Resources Administration/Department of Social Services',
- [ ] overabbrev = 'NYCHRA/DSS',
- [ ] overlevel = NULL,
- [ ] capacity = NULL,
- [ ] captype = NULL,
- [ ] proptype = NULL
